[package]
name = "flatland"
version = "0.8.0"
edition = "2021"
authors = ["Nova King <technobaboo@proton.me>"]
description = "Flat panel UI client for Stardust XR like SimulaVR or xrdesktop"
license = "MIT"
repository = "https://github.com/StardustXR/flatland/"
homepage = "https://stardustxr.org"

[dependencies]
glam = { version = "0.22.0", features = ["mint"] }
mint = "0.5.9"
manifest-dir-macros = "0.1.16"
lazy_static = "1.4.0"
tokio = { version = "1.24.2", features = ["full"] }
num = "0.4.0"
xkbcommon = { version = "0.5.0", features = ["x11"] }
num-traits = "0.2.15"
input-event-codes = "5.16.8"
stardust-xr-molecules = "0.17.0"
rustc-hash = "1.1.0"
flexbuffers = "2.0.0"
parking_lot = "0.12.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing = "0.1.37"
color-eyre = "0.6.2"

# [patch.crates-io]
# stardust-xr-molecules = { path = "../../molecules" }
# stardust-xr-fusion = { path = "../../core/fusion" }